### PR TITLE
Update playbook to use Cantaloupe 4.1.7

### LINKED ISSUE #1687: Update Cantaloupe to 4.1+
We currently use a pretty dated, but reliable version of Cantaloupe in the playbook setup (3.3.1). Cantaloupe 4.0.0 has been out since Oct. 2018. It'd be good to update the playbook setup to use a more recent release.

If Cantaloupe is updated to 4.1+, it _should_ help resolve [an issue with running the Drupal site with HTTPS and reverse proxying Cantaloupe](https://github.com/cantaloupe-project/cantaloupe/issues/266). :crossed_fingers:

### PR DESCRIPTION
**Pull request by ruebot**
**GitHub Issue**: https://github.com/Islandora/documentation/issues/1687

# What does this Pull Request do?

Updates the playbook to use Cantaloupe 4.1.7. 

Depends on: https://github.com/Islandora-Devops/islandora-playbook/pull/194

With https://github.com/Islandora-Devops/islandora-playbook/pull/194 it resolved resolves https://github.com/Islandora/documentation/issues/1687.

# What's new?

*LOTS* of new Cantaloupe configuration variables. I kept the Ansible variable names the same where they changed in the config. If y'all want them changed, happy to do it. 

# How should this be tested?

- Update `$VagrantBox` to use `ubuntu/bionic64` in `Vagrantfile`
- Update repo and branch for Cantaloupe playbook in `requirements.yml`

Screenshot from 2020-11-12 19-46-20

- Add an Islandora Object, with an image, and you should see this:

Screenshot_2020-11-12 Test Islandora 8

- Go to http://localhost:8080/cantaloupe/admin and use `admin/islandora` and you should see this:
Screenshot_2020-11-12 Cantaloupe Image Server

# Additional Notes:

I have a note about Grok on 

# Interested parties
@elizoller @seth-shaw-unlv

### CODE REVIEW

**Comment by elizoller** [comment]
I'll give this a whirl today

**Comment by elizoller** [comment]
Alright - so i definitely got 4.1.7 of cantaloupe when i pulled this in - i just haven't been able to verify that its working for an image yet

**Comment by elizoller** [comment]
Alright - confirmed image working with OSD

**Review by elizoller — APPROVED** [review]
Confirmed a full build works and installs Cantaloupe 4.1.7

**Comment by elizoller** [comment]
I'd appreciate it if at least one other person would confirm - perhaps @seth-shaw-unlv since he has already used 4.1.7

**Comment by seth-shaw-unlv** [comment]
Sorry I missed the mention, @elizoller & @ruebot! I'll see if I can spin this up today.

**Comment by seth-shaw-unlv** [comment]
FINALLY got ubuntu to build on my slow connection. It appears to be working fine. Now I'll destroy and rebuild on centos 7 just to be sure.

**Review by seth-shaw-unlv — APPROVED** [review]
🚀

**Pull request merged**
